name: dynamic_navigation_drawer
description: This flutter plugin is for dynamic navigation drawer
version: 0.0.3
homepage: https://github.com/satyambarsainya/dynamic_navigation_drawer

environment:
  sdk: ">=2.16.1 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.objectx.technologies.dynamic_navigation_drawer
        pluginClass: DynamicNavigationDrawerPlugin
      ios:
        pluginClass: DynamicNavigationDrawerPlugin
      windows:
        pluginClass: DynamicNavigationDrawerPlugin
      web:
        pluginClass: DynamicNavigationDrawerWeb
        fileName: dynamic_navigation_drawer_web.dart